### ISSUE TITLE
Question about repo activity

### ISSUE THREAD

**Issue by davids91** [Adam-Gleave/svo-rs#1]
Hi! I found your work through extensive search of a competent sparse octree solution and yours seem to be the best one yet! 
 Are you still in development of this? 
 Are you planning to deploy your work to crates.io or libs.rs?

**Comment by Adam-Gleave** [comment]
Hello!

I haven't worked on this in quite some time, but I'd be up for releasing to crates.io if this reached some level of completeness. If you find yourself using it and want to make contributions, please feel free to do so!

**Comment by davids91** [comment]
Yeah, for sure! The examples got me hooked up!

**Comment by davids91** [comment]
I pushed some changes to my fork, and made pull requests here ( they're numbered ), would you please have a look at them to see if they are something you would want in your repo?

**Comment by Adam-Gleave** [comment]
Thanks very much! I will try and get around to these on the weekend if I can, I'm pretty busy nowadays 😅 Certainly appreciate the contributions, though.

**Comment by davids91** [comment]
Much appreciated! :) I actually did the changes in my for, if that helps, I respect if you are busy!

**Comment by davids91** [comment]
In any case, my fork has these changes on main, feel free to spook around :)
